### ISSUE TITLE
[brackets] in task results in error: missing desc

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-vim#3]
All in the title.

**Comment by soywod** [comment]
Could you give me the command you tried?

**Comment by norseghost** [comment]
In vim:

`This is a description [with brackets] +and +tags`

<esc>:w

AFAIK. will add a better description when I’m at my computer later

**Comment by norseghost** [comment]
huh. There must have been another triggering cause - retested @ computer, and things worked as expected.

maybe the parentheses bug? I was adding many lines at once at some point...

Will open a new issue if I experience problems.

**Comment by soywod** [comment]
Yes, could be linked to the parentheses bug. Let me know!
