### ISSUE TITLE
Empty lines when saving a changed buffer results in errors

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-vim#4]
It might make more sense to ignore them.

(this was the behavior I referenced in #3 - i found the culprit!)

**Comment by soywod** [comment]
The error disappeared with the CLI [v0.2.0](https://github.com/unfog-io/unfog-cli/releases/tag/v0.2.0), but instead it was creating an empty task - which I just fixed in 9540aedf09b12e896b1fb6702d0d768d917f75a9.
