### ISSUE TITLE
Update the go to context gif - command shows "done" rather than "+done"

### ISSUE THREAD

**Issue by Rahel-A** [unfog-io/unfog-vim#6]
NVIM v0.3.8

These commands work as expected:
```Go to context: +gui``` shows me tasks with the tag +gui
```Go to context: ``` clears the context and shows me all my tasks.

```Go to context: +gui done```, this is what I was trying to run as that's what the gif was showing.

```Go to context: +gui +done```, this is the command that succeeds for me.

**Comment by soywod** [comment]
Indeed, the gif is not up-to-date, I will change it. The correct way is `+gui +done`. Done is considered as a [special tag](https://github.com/unfog-io/unfog-cli#context).
